main = "src/worker.ts"
name = "feed2social"
compatibility_date = "2025-04-02"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
# Every 5 minutes
crons = ["*/5 * * * *"]

[vars]
BSKY_ID = "lacolaco.bsky.social"
NOTION_DATA_SOURCE_ID = "800e0eb6-03c4-4fd0-81a3-c4f11fa107eb"
SENTRY_DSN = "https://2037e01514d53cf9de52433a5d5d5626@o4505734726549504.ingest.sentry.io/4505734743523328"
SENTRY_RELEASE = "${SENTRY_RELEASE}"
