compatibility_date = "2023-05-15"
main = "src/worker.ts"
name = "notion2rss"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
# Every 5 minutes
crons = ["*/5 * * * *"]

[vars]
NOTION_DATABASE_ID = "bce0d0a9147e468ca227788ca1797d28"

[[d1_databases]]
binding = "DB"
database_id = "f35702c2-9948-4a64-8fa3-9db1cea4a534"
database_name = "feed2social"
