name: deploy-production

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.prettierrc'
      - '.editorconfig'
      - '.gitignore'
      - '.github/**'
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: 'package.json'
      - run: corepack enable
      - run: pnpm install
      - name: Replace "${SENTRY_RELEASE}" in wrangler.toml with the current commit hash
        run: sed -i "s/\${SENTRY_RELEASE}/${{ github.sha }}/g" wrangler.toml
      - run: pnpm run deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Create Sentry release
        uses: getsentry/action-release@00ed2a6cc2171514e031a0f5b4b3cdc586dc171a # v3.1.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
