name: deploy-production

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.prettierrc'
      - '.editorconfig'
      - '.gitignore'
      - '.github/**'
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - run: corepack enable
      - run: pnpm install
      - name: Replace "${SENTRY_RELEASE}" in wrangler.toml with the current commit hash
        run: sed -i "s/\${SENTRY_RELEASE}/${{ github.sha }}/g" wrangler.toml
      - run: pnpm run deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: ${{ github.sha }}
